name: liquid_glass_navbar
description: A beautiful frosted-glass bottom navigation bar with bubble animation and auto-hide effect.
version: 1.0.2
homepage: https://github.com/Karf2411/lquid_glass_navbar_package
repository: https://github.com/Karf2411/lquid_glass_navbar_package

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true